server:
  port: 8080

management:
  ##  port: 8185
  metrics:
    export:
      graphite:
        host: graphite.aem.local
        port: 2003
        protocol: plaintext

# force the banner to appear in the log file, this is required
# for it to show on logentries
spring:
  application:
    name: "dci-service"
  main:
    banner_mode: LOG

# The region and queues can be set at runtime either via -D option or environment
# variables such as sqs_queues_patchbundlequeue=blahblah
sqs:
  #  region: "blah"
  queues:
    dattoContinuityDeviceQueue: "${PLATFORM_NAME}DCIDeviceQueue.fifo"

dci:
  readTimeout: 60000
  connectTimeout: 60000
  portalApiUrl: https://api.datto.com
  platform: ${PLATFORM_NAME}
  localstack:
    enabled: false