name: Gitlab CI/CD

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:  

  build: 
    runs-on: ubuntu-latest

    steps: 
      - name: Trigger Gitlab  
        run: echo Trigger Gitlab CI/CD
      - name: Trigger GitLab CI Job  
        uses: appleboy/gitlab-ci-action@v0.0.2
        with:
          token: glptt-7169fba3b1cd590dbe1ac933d5a4732de43d27b0
          ref: main
          project_id: 22192
