name: Mirror to GitLab

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Push to GitLab
      run: |
        git remote add gitlab https://VqRMQWHUebiUqsyjTh6n@gitlab.datto.net/rmm/repos/experiments/dci-clone-testing.git
        git push --mirror gitlab
      env:
        GITLAB_TOKEN: VqRMQWHUebiUqsyjTh6n
