# .github/workflows/sync-to-gitlab.yml
name: Sync to GitLab

on:
  push:
    branches:
      - main  # Adjust if you are using a different branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Configure Git
        run: |
          git config --global user.name "SThirikovalluru"
          git config --global user.email "sthirikovalluru@datto.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://gitlab.datto.net/rmm/repos/experiments/dci-clone-testing.git

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: VqRMQWHUebiUqsyjTh6n
        run: |
          git push https://gitlab-ci-token:VqRMQWHUebiUqsyjTh6n@gitlab.com/sthirikovalluru/dci-clone-testing.git main
